version: "3.9"
services:
  app:
    build:
      dockerfile: ./Docker/PhpFpm81Dockerfile
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  redis:
    image: redis
    ports:
      - "6379:6379"
